name: Python Tests

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Replace with your dependencies

      - name: Run tests
        run: |
          pytest ex1_test.py  # Replace with your test file
